[font]
size = 12.0

[font.bold]
family = "MesloLGM Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"
