
# ~/.config/starship.toml

# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format = """$all"""

# https://starship.rs/advanced-config/#continuation-prompt
continuation_prompt = '▶▶ '

[battery]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = '[V](bold green) '
