
# ~/.config/starship.toml

# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format = """$all"""

# https://starship.rs/advanced-config/#continuation-prompt
continuation_prompt = '▶▶ '

 # Insert a blank line between shell prompts
add_newline = true

[battery]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[;](green)'
error_symbol = '[;](red)'
vimcmd_symbol = '[V](bold green) '


# Fill character (empty space) between the left and right prompt
[fill]
symbol = " "

# @TODO etre 2 lignes 

[cmd_duration]
format = 'took [$duration]($style) '
